INSERT INTO TABLE_ATTRIBUTE (NAME) VALUES ('COLOR');
INSERT INTO TABLE_ATTRIBUTE (NAME) VALUES ('DIMENSIONS');

INSERT INTO TABLE_CATEGORY (NAME) VALUES ('HANDBAG');
INSERT INTO TABLE_CATEGORY (NAME) VALUES ('WALLET');
INSERT INTO TABLE_CATEGORY (NAME) VALUES ('BAGPACK');
INSERT INTO TABLE_CATEGORY (NAME) VALUES ('WAIST BAG');

INSERT INTO TABLE_GROUP (NAME) VALUES ('WOMAN');
INSERT INTO TABLE_GROUP (NAME) VALUES ('MAN');
INSERT INTO TABLE_GROUP (NAME) VALUES ('KIDS');
INSERT INTO TABLE_GROUP (NAME) VALUES ('UNISEX');

INSERT INTO TABLE_PRODUCT (NAME, DESCRIPTION, MODEL, PRICE, ACTIVE, CATEGORY_ID, GROUP_ID) VALUES ('Grid handbag', 'Classic grid design', 'M0123', 1234.5, 1, 1, 1);

INSERT INTO PRODUCT_ATTR (PRODUCT_ID, ATTR_ID) VALUES (1, 1);
INSERT INTO PRODUCT_ATTR (PRODUCT_ID, ATTR_ID) VALUES (1, 2);

INSERT INTO PRODUCT_ATTR_VAL (PRODUCT_ATTR_ID, VAL) VALUES (1, 'RED');
INSERT INTO PRODUCT_ATTR_VAL (PRODUCT_ATTR_ID, VAL) VALUES (1, 'BLACK');
INSERT INTO PRODUCT_ATTR_VAL (PRODUCT_ATTR_ID, VAL) VALUES (2, '50 x 35 x 60');

INSERT INTO TABLE_STOCK (PRODUCT_ID, PRODUCT_ATTR_VAL_ID, AMOUNT) VALUES (1, 1, 10);
INSERT INTO TABLE_STOCK (PRODUCT_ID, PRODUCT_ATTR_VAL_ID, AMOUNT) VALUES (1, 2, 30);